import type { NextPage } from "next";
import Head from "next/head";
import Intro from "../src/components/Intro";
import Syntax from "../src/components/Syntax";
import Extensions from "../src/components/Extensions";
import classes from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Intro />
        <Syntax />
        <Extensions />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
